DROP TABLE IF EXISTS job;

CREATE TABLE job(
    id SERIAL PRIMARY KEY,
    title VARCHAR(2000) NOT NULL,
    company VARCHAR(2000) NOT NULL,
    location VARCHAR(2000) NOT NULL,
    datepost VARCHAR(2000) NOT NULL,
    URL VARCHAR(2000) NOT NULL
);